import { API_ENDPOINT } from "../ApiRootEndpoint.ts";

export const NOTIFICATION_END_POINT = {
    GET_NOTIFICATION: `${API_ENDPOINT.NOTIFICATION}`, // --> &pageIndex=1
    READ_NOTIFICATION: `${API_ENDPOINT.NOTIFICATION}/read`, // --> /read/B71BFA83-38BF-4E62-966F-C304D0643FA9
    READ_ALL_NOTIFICATION: `${API_ENDPOINT.NOTIFICATION}/readAll`, // --> /readAll
}